### ISSUE TITLE
json TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by changer2222** [Zero-S1/JD_tools#1]
Traceback (most recent call last):
  File "./jd/JD_plantBean.py", line 415, in <module>
    _plantChannelTaskList(cookies)
  File "./jd/JD_plantBean.py", line 334, in _plantChannelTaskList
    result = json(response.text)
TypeError: 'module' object is not callable

请问这是什么解决？
python3环境下。
昨天还能用，今天就不行了。
我本地是有json的。
response.text内容已得到了

**Comment by Zero-S1** [comment]
写错了，订正为 json.loads(response.text)    😂

**Comment by changer2222** [comment]
谢谢
