### ISSUE TITLE
云函数运行报错

### ISSUE THREAD

**Issue by leecheng310** [Zero-S1/JD_tools#84]
返回数据:

{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 16, in main_handler\n    tmp = __import__(i)\n  File \"/var/user/count_bean.py\", line 3, in \u003cmodule\u003e\n    import jdCookie\n  File \"/var/user/jdCookie.py\", line 37, in \u003cmodule\u003e\n    pt_pin = re.findall(r'pt_pin=(.*?)\u0026', line)[0]\nIndexError: list index out of range","statusCode":430}

日志:

START RequestId:9278d3c2-6c0e-477b-8ba8-7a47f9b54e65

开始执行  count_bean.py

执行自GitHub action 

ERROR RequestId:9278d3c2-6c0e-477b-8ba8-7a47f9b54e65 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 16, in main_handler\n    tmp = __import__(i)\n  File \"/var/user/count_bean.py\", line 3, in \u003cmodule\u003e\n    import jdCookie\n  File \"/var/user/jdCookie.py\", line 37, in \u003cmodule\u003e\n    pt_pin = re.findall(r'pt_pin=(.*?)\u0026', line)[0]\nIndexError: list index out of range","statusCode":430} 

END RequestId:9278d3c2-6c0e-477b-8ba8-7a47f9b54e65

Report RequestId:9278d3c2-6c0e-477b-8ba8-7a47f9b54e65 Duration:3ms Memory:128MB MemUsage:16.859375MB

感觉是cookie填写问题？

**Comment by leecheng310** [comment]
> 返回数据:
> 
> {"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n File "/var/user/index.py", line 16, in main_handler\n tmp = **import**(i)\n File "/var/user/count_bean.py", line 3, in \u003cmodule\u003e\n import jdCookie\n File "/var/user/jdCookie.py", line 37, in \u003cmodule\u003e\n pt_pin = re.findall(r'pt_pin=(.*?)\u0026', line)[0]\nIndexError: list index out of range","statusCode":430}
> 
> 日志:
> 
> START RequestId:9278d3c2-6c0e-477b-8ba8-7a47f9b54e65
> 
> 开始执行 count_bean.py
> 
> 执行自GitHub action
> 
> ERROR RequestId:9278d3c2-6c0e-477b-8ba8-7a47f9b54e65 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n File "/var/user/index.py", line 16, in main_handler\n tmp = **import**(i)\n File "/var/user/count_bean.py", line 3, in \u003cmodule\u003e\n import jdCookie\n File "/var/user/jdCookie.py", line 37, in \u003cmodule\u003e\n pt_pin = re.findall(r'pt_pin=(.*?)\u0026', line)[0]\nIndexError: list index out of range","statusCode":430}
> 
> END RequestId:9278d3c2-6c0e-477b-8ba8-7a47f9b54e65
> 
> Report RequestId:9278d3c2-6c0e-477b-8ba8-7a47f9b54e65 Duration:3ms Memory:128MB MemUsage:16.859375MB
> 
> 感觉是cookie填写问题？

# 方案1 本地执行、云服务器、云函数等等   下载到本地，填写参数，执行
cookies1 = {'pt_key': 'XXXXXX',  # cookie参数填写，填写完注意不要上传
    'pt_pin': 'XXXXXXX',}
cookiesLists = [cookies1, ]  # 多账号准备

**Comment by leecheng310** [comment]
是JDCOOKIE.PY里这么个写法么，‘’单引号是否要保留
能在云函数里的环境变量填写么

**Comment by leecheng310** [comment]
另 action里执行也报错  

Run python3 count_bean.py
Traceback (most recent call last):
  File "count_bean.py", line 3, in <module>
    import jdCookie
  File "/home/runner/work/JD_tools-1/JD_tools-1/jdCookie.py", line 42, in <module>
    pt_pin = re.findall(r'pt_pin=(.*?)&', line)[0]
IndexError: list index out of range
执行自GitHub action
Error: Process completed with exit code 1.


https://github.com/leecheng310/JD_tools-1

小白求教
